export const mock_notifications = [
  {
    type: 'add',
    description: 'Проект «Гиперлуп» опубликован на Витрине и теперь доступен пользователям',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» переведён в статус Доработка',
    time: '',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» переведён в статус Доработка',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён Модератором',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
];

export const mock_projects = [
	{
		id: 1,
		image_logo: 'kodiki.png',
		project_name: 'Кодики',
		tagline: '',
		amount_of_investment: '5 000 000',
		description: 'Мы познакомим тебя с самыми талантливыми людьми твоего города, каждый из которых может стать собеседником, ментором, партнёром',
		round_ends: '20.05.2023',
		tags: ['Образование','Стажировки и практики', 'Информационные технологии'],
		price: '20 000 000',
		participation_conditions: ''
	},
	{
		id: 2,
		image_logo: 'ladado.png',
		project_name: 'Labado',
		tagline: 'Платформа креативных индустрий',
		amount_of_investment: '20 000 000',
		description: 'Labado - это место, где художники, дизайнеры, видеографы и многие другие, могут находить клиентов и вступать в коллаборации',
		round_ends: '20.05.2023',
		tags: ['Креативные индустрии','Коллаборации', 'UI/UX', 'Сообщество'],
		price: '100 000 000',
		participation_conditions: ''
	},	
	{
		id: 3,
		image_logo: 'melioracia.png',
		project_name: 'Мелиорация',
		tagline: 'Осушение польдерных земель',
		amount_of_investment: '10 000 000',
		description: 'Продукт, имеющий решение по сбору аналитики с помощью полевых датчиков и прогнозированию погодных условий, объединивший это в удобном веб-интерфейсе',
		round_ends: '20.05.2023',
		tags: ['Сельское хозяйство','Экология', 'UI/UX'],
		price: '40 000 000',
		participation_conditions: ''
	},
	{
		id: 4,
		image_logo: 'terka.png',
		project_name: 'Тёрка',
		tagline: 'знакомства и коллаборации',
		amount_of_investment: '10 000 000',
		description: 'Мы познакомим тебя с самыми талантливыми людьми твоего города, каждый из которых может стать собеседником, ментором, партнёром',
		round_ends: '20.05.2023',
		tags: ['Знакомства','Коллаборации', 'UI/UX', 'Креативные индустрии'],
		price: '25 000 000',
		participation_conditions: ''
	},
]