export const mock_notifications = [
  {
    type: 'add',
    description: 'Проект «Гиперлуп» опубликован на Витрине и теперь доступен пользователям',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» переведён в статус Доработка',
    time: '',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» переведён в статус Доработка',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён Модератором',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
	{
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'Проект «Гиперлуп» завершён',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
];